language: python

sudo: false

cache: pip

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6-dev"
    - "nightly" # currently points to 3.7
    - "pypy"
    - "pypy3"

before_script:
    - "export PYTHONPATH=$PYTHONPATH:`pwd`"
    - "uname -a"
    - "cd tests"

script:
    - py.test --verbose

notifications:
    email:
        receipients:
            - arek.bulski@gmail.com
